runtime: nodejs10

env_variables:
  DB_HOST: ${_DB_HOST}
  DB_PATH: ${_DB_PATH}
  DB_USER: ${_DB_USER}
  DB_PASS: ${_DB_PASS}
  DB_DATABASE: ${_DB_DATABASE}
  DATABASE_URL: ${_DATABASE_URL}
  SECRET: ${_SECRET}
  SENDGRID: ${_SENDGRID}
  PAGARME_KEY: ${_PAGARME_KEY}
