runtime: nodejs10

env_variables:
  DB_HOST: /cloudsql/api-webstock:us-central1:database-webstock
  DB_PATH: /cloudsql/api-webstock:us-central1:database-webstock
  DB_USER: root
  DB_PASS: Jose@100
  DB_DATABASE: webstock
  DATABASE_URL: mysql://root:Jose@100@35.192.180.232/webstock
  SECRET: c1a8974e97154a5615b02115ad02d226
  SENDGRID: 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
  PAGARME_KEY: KEY
