runtime: nodejs10

# [START env]
env_variables:
  DB_HOST: /cloudsql/webstock:southamerica-east1:webstock-database
  DB_PATH: /cloudsql/webstock:southamerica-east1:webstock-database
  DB_USER: megres
  DB_PASS: Jose1000
  DB_DATABASE: webstock
  DATABASE_URL: mysql://megres:Jose1000@34.95.189.55/webstock
  SECRET: 1234
  SENDGRID: KEY
  PAGARME_KEY: ak_test_L8sX32jy2TBPAd8plODYnbxTQWysVL
# [END env]
