steps:
  - name: gcr.io/cloud-builders/npm
    args: ["install"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]

  - name: 'bash'
    args: ['rm', "app.yaml"]


timeout: "1600s"