steps:
  - name: gcr.io/cloud-builders/npm
    args: ["install"]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]


  - name: 'ubuntu'
    env:
    - BUILD=AEC CARALHO FGUNCO
    - PROJECT=$PROJECT_ID
    - REV=$REVISION_ID
timeout: "1600s"